In [43]:
import numpy as np
arr = []
x = []
n = 3
for _ in range(n):
    string = [float(i) for i in input().split()]
    arr.append(string)

for i in range(3):
    x.append(arr[i][n])
x = np.array(x)
arr = np.array(arr)
a = np.copy(arr)
a = np.delete(a, n, 1)


0.1 12 -0.13 0.1
0.12 0.71 0.15 0.26
-0.13 0.15 0.63 0.38


In [44]:
b = np.zeros((n, n))
y = np.zeros(n)
g = np.zeros(n)
c = np.zeros((n, n))

try:
    for i in range(n):
        c[i][i] = 1

    for i in range(n):
        b[i][0] = a[i][0]
        c[0][i] = a[0][i]/b[0][0]

    for i in range(1, n):
        for j in range(1, i+1):
            s = sum([b[i][k]*c[k][j] for k in range(j)])
            b[i][j] = a[i][j] - s

        for j in range(i + 1, n):
            s = sum([b[i][k] * c[k][j] for k in range(i)])
            c[i][j] = 1/b[i][i] * (a[i][j] - s)


    y[0] = x[0] / b[0][0]
    for i in range(1, n):    
        s = sum([b[i][k] * y[k] for k in range(i)])
        y[i] = 1/b[i][i] * (x[i] - s)

    g[n-1]=y[n-1]    
    for i in range(n-1,-1,-1):
        s = sum([c[i][k]*g[k] for k in range(i + 1, n)])
        g[i] = y[i] - s

        
    print("b:")
    print(b)  
    print("c:")  
    print(c)
    print("y:")
    print(y)
    print("РЕШЕНИЕ:")
    print(g)

except:   
    print("НЕ МОГУ РЕШИТЬ (") 

b:
[[  0.1          0.           0.        ]
 [  0.12       -13.69         0.        ]
 [ -0.13        15.75         0.81304529]]
c:
[[ 1.00000000e+00  1.20000000e+02 -1.30000000e+00]
 [ 0.00000000e+00  1.00000000e+00 -2.23520818e-02]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
y:
[ 1.         -0.01022644  0.82537404]
РЕШЕНИЕ:
[1.08630001 0.00822239 0.82537404]
