In [89]:
import numpy as np
n = 3
# arr = []
array = []
index = []
# result = []
for _ in range(n):
    string = [float(i) for i in input().split()]
    array.append(string)
array = np.array(array)
a = np.copy(array)
# print(array,"\n")
print(a)


0.1 12 -0.13 0.1
0.12 0.71 0.15 0.26
-0.13 0.15 0.63 0.38
[[ 0.1  12.   -0.13  0.1 ]
 [ 0.12  0.71  0.15  0.26]
 [-0.13  0.15  0.63  0.38]]


In [90]:
a = np.copy(array)

arr = np.array([])
# print(arr)
index.clear()
# string = []
# print(string)

In [91]:
print(a)
flag = True
while len(a) > 0 and flag:
    aMax = a[0][0]
    for i in range(len(a)):
        for j in range(len(a)):
            if aMax <= a[i][j]:
                aMax = a[i][j]
                p = i
                q = j
                
    print("коэффициенты максимального элемента:",p, q)
    if aMax == 0:
        flag = False 
        print("Ошибка в матрице!")
        break
    print()

    for i in range(len(a)):
        m = a[i][q] / a[p][q]
        for j in range(len(a)+1):
            if i == p:
                break
            a[i][j] = a[i][j] - a[p][j] * m
        
    print("Матрица:")
    print(a, "\n")
    string = np.array([])
    
    # for i in range(n+1-len(a[p])):
    #     string.append(0) 
    string = np.append(string, a[p])
    for i in index[::-1]:
        string = np.insert(string, i, 0)
    index.append(q)

    arr = np.append(arr, np.array(string))
    #np.append(x, a[p])
    a = np.delete(a, p, 0)
    a = np.delete(a, q, 1)

    print(a, "\n")

if flag:    
    arr.shape = (3, 4)
    print("arr :",arr, sep = "\n")
    print("index :",index)


[[ 0.1  12.   -0.13  0.1 ]
 [ 0.12  0.71  0.15  0.26]
 [-0.13  0.15  0.63  0.38]]
коэффициенты максимального элемента: 0 1

Матрица:
[[ 0.1        12.         -0.13        0.1       ]
 [ 0.11408333  0.          0.15769167  0.25408333]
 [-0.13125     0.          0.631625    0.37875   ]] 

[[ 0.11408333  0.15769167  0.25408333]
 [-0.13125     0.631625    0.37875   ]] 

коэффициенты максимального элемента: 1 1

Матрица:
[[ 0.14685124  0.          0.15952451]
 [-0.13125     0.631625    0.37875   ]] 

[[0.14685124 0.15952451]] 

коэффициенты максимального элемента: 0 0

Матрица:
[[0.14685124 0.15952451]] 

[] 

arr :
[[ 0.1        12.         -0.13        0.1       ]
 [-0.13125     0.          0.631625    0.37875   ]
 [ 0.14685124  0.          0.          0.15952451]]
index : [1, 1, 0]


In [92]:
v = arr[:, 3]
m = arr[:, [0, 1, 2]]
print("ОТВЕТ:")
print(np.linalg.solve(m, v))

ОТВЕТ:
[1.08630001 0.00822239 0.82537404]
