In [2]:
import numpy as np
arr = []
x = []
for _ in range(4):
    string = [float(i) for i in input().split()]
    arr.append(string)

arr = np.array(arr)
print(arr)

 0.13 0.27 -0.22 -0.18 1.21
-0.21 0 -0.45 0.18 -0.33
0.12 0.13 -0.33 0.18 -0.48
0.33 -0.05 0.06 -0.28 -0.17
[[ 0.13  0.27 -0.22 -0.18  1.21]
 [-0.21  0.   -0.45  0.18 -0.33]
 [ 0.12  0.13 -0.33  0.18 -0.48]
 [ 0.33 -0.05  0.06 -0.28 -0.17]]


In [14]:
for i in range(4):
    arr[i][i] = arr[i][i] - 1
print(arr)


[[-3.87  0.27 -0.22 -0.18  1.21]
 [-0.21 -4.   -0.45  0.18 -0.33]
 [ 0.12  0.13 -4.33  0.18 -0.48]
 [ 0.33 -0.05  0.06 -4.28 -0.17]]


In [15]:
#Метод простых итераций
l = [0, 0, 0, 0]
k = [10, 10, 10, 10]
while (abs(k[0] - l[0]) > 0.00001 or abs(k[1] - l[1]) > 0.00001 or abs(k[2] - l[2]) > 0.00001 or abs(k[3] - l[3]) > 0.00001):
    l = k[:]
     
    for i in range(4):
        s = 0
        for j in range(4):
            if i==j:
                s += arr[i][4]
            else:
                s += arr[i][j]*l[j]
        k[i] = s / (-arr[i][i])
        # k[0] = (arr[0][0]*l[0]*0+arr[0][1]*l[1]+arr[0][2]*l[2]+arr[0][3]*l[3]+arr[0][4])/(-arr[0][0])
        # k[i] = (sum([arr[i][k]*l[k]*p for k in range(1,4) if i==k p = 0 else p = 1]) + arr[i][4]) / (-arr[i][i])
    # k[0] = (arr[0][0]*l[0]*0+arr[0][1]*l[1]+arr[0][2]*l[2]+arr[0][3]*l[3]+arr[0][4])/(-arr[0][0])
    # k[1] = (arr[1][0]*l[0]+arr[1][1]*l[1]*0+arr[1][2]*l[2]+arr[1][3]*l[3]+arr[1][4])/(-arr[1][1])
    # k[2] = (arr[2][0]*l[0]+arr[2][1]*l[1]+arr[2][3]*l[3]+arr[2][4])/(-arr[2][2])
    # k[3] = (arr[3][0]*l[0]+arr[3][1]*l[1]+arr[3][2]*l[2]+arr[3][4])/(-arr[3][3])
    print(f"x1 = {k[0]}, x2 = {k[1]}, x3 = {k[2]}, x4 = {k[3]}")
    print(f"        d1 = {abs(k[0] - l[0])}, d2 = {abs(k[1] - l[1])}, d3 = {abs(k[2] - l[2])}, d4 = {abs(k[3] - l[3])}")
    

x1 = -0.023255813953488334, x2 = -1.2825, x3 = 0.8822170900692841, x4 = 0.7546728971962617
        d1 = 10.023255813953488, d2 = 11.2825, d3 = 9.117782909930716, d4 = 9.245327102803738
x1 = 0.1379318136148399, x2 = -0.14656821202640455, x3 = -0.11863154184274631, x4 = -0.014162708691704232
        d1 = 0.16118762756832822, d2 = 1.1359317879735955, d3 = 1.0008486319120304, d4 = 0.768835605887966
x1 = 0.30983845207307026, x2 = -0.07703269364859683, x3 = -0.11202109410950545, x4 = -0.0290355101440064
        d1 = 0.17190663845823037, d2 = 0.06953551837780772, d3 = 0.006610447733240862, d4 = 0.01487280145230217
x1 = 0.31500573778937757, x2 = -0.08747074360299711, x3 = -0.10578753527747582, x4 = -0.01650068733178208
        d1 = 0.005167285716307313, d2 = 0.010438049954400286, d3 = 0.006233558832029626, d4 = 0.01253482281222432
x1 = 0.31334012421394214, x2 = -0.08787923444515648, x3 = -0.1054366355319596, x4 = -0.015892948940655165
        d1 = 0.0016656135754354318, d2 = 0.0004084908421593


для проверки вольфрам:

x = 0.13x +0.27y-0.22z-0.18c +1.21, y = -0.21x-0.45z+0.18c-0.33, z = 0.12x+0.13y-0.33z+0.18c-0.48, c=0.33x-0.05y+0.06z-0.28c-0.17

In [16]:
#Метод Зейделя
l = [0, 0, 0, 0]
k = [10, 10, 10, 10]
while (abs(k[0] - l[0]) > 0.00001 or abs(k[1] - l[1]) > 0.00001 or abs(k[2] - l[2]) > 0.00001 or abs(k[3] - l[3]) > 0.00001):
    l = k[:]
    for i in range(4):
        s = 0
        for j in range(4):
            if i==j:
                s += arr[i][4]
            elif i > j:
                s += arr[i][j]*k[j]
            else:
                s += arr[i][j]*l[j]
        k[i] = s / (-arr[i][i])
    print(f"x1 = {k[0]}, x2 = {k[1]}, x3 = {k[2]}, x4 = {k[3]}")
    print(f"        d1 = {abs(k[0] - l[0])}, d2 = {abs(k[1] - l[1])}, d3 = {abs(k[2] - l[2])}, d4 = {abs(k[3] - l[3])}")
    

x1 = -0.023255813953488334, x2 = -0.756279069767442, x3 = 0.2814995434770932, x4 = -0.0287314234830966
        d1 = 10.023255813953488, d2 = 10.756279069767443, d3 = 9.718500456522907, d4 = 10.028731423483096
x1 = 0.24523162992888567, x2 = -0.12833627326917882, x3 = -0.10910567578764072, x4 = -0.020841843225997015
        d1 = 0.268487443882374, d2 = 0.6279427964982631, d3 = 0.3906052192647339, d4 = 0.007889580257099585
x1 = 0.31087958311919434, x2 = -0.08748467253281798, x3 = -0.10573186818375115, x4 = -0.016210143933422908
        d1 = 0.06564795319030867, d2 = 0.040851600736360835, d3 = 0.00337380760388957, d4 = 0.004631699292574107
x1 = 0.3133224742440776, x2 = -0.08778405120414612, x3 = -0.10548061331530388, x4 = -0.016014770499571337
        d1 = 0.002442891124883273, d2 = 0.0002993786713281349, d3 = 0.00025125486844726486, d4 = 0.0001953734338515714
x1 = 0.31327821700107755, x2 = -0.0878012020670656, x3 = -0.10547423300658476, x4 = -0.016017893052964065
        d1 = 4.4257243000